# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/319e73f2-d9f4-4be7-a99e-b8673bfec4fb";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C7E0-9D87";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
    fileSystems."/mnt/backup" = {
  device = "/dev/disk/by-uuid/07d224c8-09ef-4fb3-9bba-0ec640900134";
  fsType = "ext4";  # or whatever you formatted it as
 };
  swapDevices =
    [ { device = "/dev/disk/by-uuid/6c0b8767-271b-4c5f-841f-a07c2d28f910"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
